# Generated by Django 2.0.3 on 2018-03-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlsize',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
