# Generated by Django 2.0.3 on 2018-03-22 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180322_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laurent',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.FabricColor'),
        ),
    ]
